"""
make_data_book.py — build docs/DATA_BOOK.md (and results/runs/INDEX.csv) from the run records
===============================================================================================
INDEX.csv is a one-line-per-run summary, rebuilt here and git-ignored, so
parallel experiment runs on different machines never conflict in git.

One dated entry per experiment run in results/runs/ (oldest first): what
was run, the exact command, git commit, settings, the one-line result and
the record file. This is the evidence section of the research data book;
the reasoning ("why we ran it, what we concluded, what we changed next")
is written by hand.

Handwritten notes: create docs/data_book_notes/<run record stem>.md and it
is inserted under that run's entry. Regenerating never touches those files.

Results produced before the run log existed (results/*.json) are listed at
the end with a warning that they have no commit/command provenance.

    python scripts/make_data_book.py
"""

import csv
import json
import subprocess
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "results" / "runs"
NOTES = REPO / "docs" / "data_book_notes"
OUT = REPO / "docs" / "DATA_BOOK.md"

SKIP_CONFIG = {"root", "acc_root", "hyd_root"}          # machine-specific paths


def first_committed(path: Path) -> str:
    """Date the file first entered git history (following renames)."""
    out = subprocess.run(["git", "log", "--follow", "--format=%ad", "--date=format:%d %b %Y",
                          "--", str(path.relative_to(REPO))], cwd=REPO, capture_output=True, text=True)
    dates = out.stdout.strip().splitlines()
    return dates[-1] if dates else "not in git"


def fmt_config(cfg: dict) -> str:
    items = [f"`{k}={v}`" for k, v in cfg.items() if k not in SKIP_CONFIG and v not in (None, [], "")]
    return ", ".join(items) or "defaults"


def entry(rec: dict, path: Path) -> str:
    ts = datetime.fromisoformat(rec["timestamp"])
    dirty = " (uncommitted changes present)" if rec.get("git_dirty") else ""
    lines = [
        f"### {ts:%d %b %Y, %H:%M} — {rec['experiment']}",
        "",
        f"- **Result:** {rec.get('summary') or '(no summary)'}",
        f"- **Command:** `{rec.get('command', '')}`",
        f"- **Code version:** commit `{rec.get('git_commit') or 'unknown'}`{dirty}; "
        f"Python {rec.get('python')}, torch {rec.get('torch')}, {rec.get('device')}",
        f"- **Settings:** {fmt_config(rec.get('config', {}))}",
        f"- **Record:** [`results/runs/{path.name}`](../results/runs/{path.name})",
    ]
    note = NOTES / f"{path.stem}.md"
    lines += ["", note.read_text(encoding="utf-8").strip() if note.exists()
              else f"*Notes: add `docs/data_book_notes/{path.stem}.md` (why this was run, "
                   f"what it shows, what was done next).*"]
    return "\n".join(lines)


def main():
    records = []
    for p in sorted(RUNS.glob("*.json")):
        try:
            records.append((json.loads(p.read_text(encoding="utf-8")), p))
        except (json.JSONDecodeError, KeyError):
            print(f"skip unreadable {p.name}")
    records.sort(key=lambda r: r[0]["timestamp"])

    parts = [
        "# Research data book — experiment log",
        "",
        f"Generated by `scripts/make_data_book.py` on {datetime.now():%d %b %Y}. "
        "Do not edit this file by hand: add notes in `docs/data_book_notes/` and regenerate.",
        "",
        f"{len(records)} recorded runs. Every number in the paper should trace to one of these "
        "entries (see `docs/CLAIMS.md`); corrections are listed in `docs/INTEGRITY_LOG.md`.",
        "",
    ]
    day = None
    for rec, p in records:
        d = rec["timestamp"][:10]
        if d != day:
            parts += [f"## {datetime.fromisoformat(d):%A %d %B %Y}", ""]
            day = d
        parts += [entry(rec, p), ""]

    legacy = sorted((REPO / "results").glob("*.json"))
    if legacy:
        parts += ["## Results from before the run log", "",
                  "These files were produced before `results/runs/` existed. They record numbers "
                  "but not the command, settings or code version that produced them, so they "
                  "carry less weight as evidence.", ""]
        for p in legacy:
            parts.append(f"- [`results/{p.name}`](../results/{p.name}) — first committed "
                         f"{first_committed(p)}")
        parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    with (RUNS / "INDEX.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["timestamp", "experiment", "git_commit", "git_dirty", "summary", "file"])
        for rec, p in records:
            w.writerow([rec["timestamp"], rec["experiment"], rec.get("git_commit"),
                        rec.get("git_dirty"), rec.get("summary"), p.name])
    NOTES.mkdir(parents=True, exist_ok=True)
    print(f"Wrote {OUT.relative_to(REPO)} and results/runs/INDEX.csv ({len(records)} runs)")


if __name__ == "__main__":
    main()
